spring:
  application:
    name: PetServiceManagement

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_service_management?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456


mybatis:

  mapper-locations: classpath:mapper/**/*.xml

  type-aliases-package: cn.edu.xaut.domain.entity

  configuration:
    map-underscore-to-camel-case: true


knife4j:
  enable: true
  setting:
    language: zh_cn